# Generated by Django 6.1.1 on 2026-09-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentplan',
            options={'ordering': ['category', 'minimum_amount'], 'verbose_name_plural': 'Investment Plans'},
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='category',
            field=models.CharField(choices=[('crypto', 'CRYPTO'), ('forex', 'FOREX'), ('oil_gas', 'OIL & GAS'), ('tesla_equities', 'TESLA / EQUITIES'), ('ai', 'AI'), ('spacex', 'SPACEX')], default='crypto', max_length=20),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='max_return',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max projected return % (e.g., 10)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='min_return',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Min projected return % (e.g., 5)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
