# Generated by Django 6.1.1 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investmentplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='gift_card_image',
            field=models.ImageField(blank=True, help_text='Upload image of gift card', null=True, upload_to='gift_cards/'),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='payment_method',
            field=models.CharField(choices=[('solana', 'Solana (SOL)'), ('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('giftcard', 'Gift Card')], default='solana', max_length=20),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Transaction Hash (TxID) for crypto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='category',
            field=models.CharField(choices=[('crypto', 'CRYPTO'), ('forex', 'FOREX'), ('tesla', 'TESLA'), ('ai', 'AI'), ('spacex', 'SPACEX')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='max_return',
            field=models.DecimalField(decimal_places=2, help_text='Max projected return %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='min_return',
            field=models.DecimalField(decimal_places=2, help_text='Min projected return %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
