# Generated by Django 6.1.1 on 2026-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_userinvestment_gift_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestment',
            name='gift_card_image',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot of crypto transfer or gift card image', null=True, upload_to='payment_proofs/'),
        ),
    ]
