# Generated by Django 6.1.1 on 2026-09-25 10:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot of crypto transfer or gift card image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
